# Generated by Django 2.2.5 on 2021-11-20 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя')),
                ('db_key', models.CharField(max_length=100)),
                ('url_yandex', models.URLField(blank=True, verbose_name='Url Яндекс карты')),
                ('url_google', models.URLField(blank=True, verbose_name='Url Google Maps')),
                ('url_flamp', models.URLField(blank=True, verbose_name='Url Flamp')),
                ('url_2gis', models.URLField(blank=True, verbose_name='Url 2Gis')),
            ],
            options={
                'verbose_name': 'Клиента',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='YandexMapsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_parse', models.CharField(blank=True, max_length=20, verbose_name='Дата парсинга')),
                ('raiting', models.IntegerField(blank=True, verbose_name='Рейтинг')),
                ('count_comments', models.IntegerField(blank=True, verbose_name='Колличество коментариев')),
                ('yandex_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientstat.ClientModel')),
            ],
            options={
                'verbose_name': 'Яндекс Карты',
                'verbose_name_plural': 'Яндекс Карты',
            },
        ),
        migrations.CreateModel(
            name='TwoGisModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_parse', models.CharField(blank=True, max_length=20, verbose_name='Дата парсинга')),
                ('raiting', models.IntegerField(blank=True, verbose_name='Рейтинг')),
                ('count_comments', models.IntegerField(blank=True, verbose_name='Колличество коментариев')),
                ('gis_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientstat.ClientModel')),
            ],
            options={
                'verbose_name': '2Gis',
            },
        ),
        migrations.CreateModel(
            name='GoogleMapsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_parse', models.CharField(blank=True, max_length=20, verbose_name='Дата парсинга')),
                ('raiting', models.IntegerField(blank=True, verbose_name='Рейтинг')),
                ('count_comments', models.IntegerField(blank=True, verbose_name='Колличество коментариев')),
                ('google_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientstat.ClientModel')),
            ],
            options={
                'verbose_name': 'Google Maps',
            },
        ),
        migrations.CreateModel(
            name='FlampModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_parse', models.CharField(blank=True, max_length=20, verbose_name='Дата парсинга')),
                ('raiting', models.IntegerField(blank=True, verbose_name='Рейтинг')),
                ('count_comments', models.IntegerField(blank=True, verbose_name='Колличество коментариев')),
                ('flamp_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientstat.ClientModel')),
            ],
            options={
                'verbose_name': 'Flamp',
            },
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_resurs', models.CharField(max_length=20, verbose_name='Источник')),
                ('comment_number', models.CharField(max_length=100, verbose_name='Номер коментария')),
                ('status_coment', models.CharField(max_length=20, verbose_name='Статус')),
                ('author_comment', models.CharField(max_length=20, verbose_name='Автор')),
                ('text_comment', models.TextField(max_length=3000, verbose_name='Текст коментария')),
                ('date_comment', models.CharField(max_length=10, verbose_name='Дата коментария')),
                ('mylike', models.IntegerField(verbose_name='Лайки')),
                ('dislike', models.IntegerField(verbose_name='Дизлайки')),
                ('comments_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientstat.ClientModel')),
            ],
        ),
    ]
